"""
Django settings for aarvi project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$yewdg-kn&x7upb4=%egufu$k4!r_i-7n4fs3g5m$^ncd%eq&&'

DEBUG = True

ALLOWED_HOSTS = ['aarvi-paints.onrender.com', 'localhost', '127.0.0.1','kubernetes.docker.internal',]

CSRF_TRUSTED_ORIGINS = [
    'https://aarvi-paints.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',  # Add localhost for development
]

# Keep these as is
CORS_ALLOWED_ORIGINS = [
    'https://aarvi-paints.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
    
# CSRF_COOKIE_HTTPONLY = False

CORS_ALLOW_CREDENTIALS = True

# CSRF_COOKIE_SAMESITE = 'Lax'  # Or 'None' if you need cross-site requests
# SESSION_COOKIE_SECURE = True  

CSRF_COOKIE_SECURE = False  # Fine for development; True for production

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Needed for HTTPS on Render

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aarvi_paint',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'ckeditor',
    'nested_admin',

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'aarvi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'aarvi_paint' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aarvi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'aarvi_paints',
#         'USER': 'postgres',
#         'PASSWORD': 'Rollys@5346',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Ensure PostgreSQL is set as the backend
        'NAME': os.getenv('DB_NAME'),  # Get the database name from the environment variable
        'USER': os.getenv('DB_USER'),  # Get the database user from the environment variable
        'PASSWORD': os.getenv('DB_PASSWORD'),  # Get the database password from the environment variable
        'HOST': os.getenv('DB_HOST'),  # Get the host from the environment variable
        'PORT': os.getenv('DB_PORT'),  # Get the port from the environment variable
    }
}

# import dj_database_url
# import os

# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL'),
#         conn_max_age=600,  
#         ssl_require=True   
#     )
# }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
import os

# Already existing:
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'aarvi_paint/static')]


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title": "Aarvi Paints Admin",
    "site_header": "Aarvi Paints",
    "site_logo": "images/logo.jpg",
    "site_brand": "Aarvi Paints",
    "welcome_sign": "Welcome to Aarvi Paints Admin Panel",
    "copyright": "Aarvi Paints",
    "custom_css": "css/admin_custom.css",

    # Optional: top menu and sidebar tweaks
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [],

    # Group models under the 'Banners' section
    "group_models": {
        "Banners": [
            "aarvi_paint.GalleryBanner",
            "aarvi_paint.HomeInteriorBanner",
            "aarvi_paint.HomeExteriorBanner",
            "aarvi_paint.HomeWaterproofingBanner",
            "aarvi_paint.AboutUsTopBanner",
            "aarvi_paint.ColorPalletsBanner",
            "aarvi_paint.ProductBanner",
            "aarvi_paint.ContactUsBanner",
            "aarvi_paint.AboutUsBottomVideoBanner",
        ],
    },

    # Optional: Icons for your models
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
}




JAZZMIN_UI_TWEAKS = {
    "theme": "minty",
    "accent": "accent-teal",
    "navbar": "navbar-light",
    "sidebar": "sidebar-light-info",
    "brand_colour": "navbar-success",
    "sidebar_nav_compact_style": False,
    "sidebar_fixed": True,
    "layout_boxed": False,
    "theme_switcher": True,
    "body_bg": "#fff2e6",
    "dark_mode_theme": "slate",
    "text_size": "text-base",
    "actions_sticky_top": True,

    "table_bg": "#f1f9ff",
    "table_header_bg": "#b3e0ff",
    "table_border_color": "#80bfff",
    "table_row_hover_color": "#e6f7ff",
    "table_text_color": "#333333",
    "table_stripe_color": "#ffebcc",
    "table_stripe_hover_color": "#ffdd99",
}


# settings.py

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
