# Generated by Django 5.2 on 2025-05-14 12:54

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Inspiration', 'Inspiration'), ('TESTIMONIAL', 'TESTIMONIAL'), ('Calculator', 'Calculator'), ('WATER_CALCULATOR', 'WATER_CALCULATOR')], max_length=200)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('url', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminContactDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('google_link', models.URLField()),
                ('social_media_links', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('placement_location', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField()),
                ('url', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.JSONField(blank=True, default=dict)),
                ('uploaded_pdf', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subcategory_names', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColourPalette',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('url', models.JSONField(blank=True, default=dict, null=True)),
                ('side_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('side_description', models.TextField()),
                ('type', models.CharField(blank=True, editable=False, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExteriorHomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('WaterProf', 'WaterProf')], max_length=200)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_images', models.JSONField(blank=True, default=dict, null=True)),
                ('type_images', models.JSONField(blank=True, default=dict, null=True)),
                ('type_description', models.TextField(blank=True, null=True)),
                ('title_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parallax',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('copyright', models.CharField(max_length=255)),
                ('app_download_links', models.JSONField(default=dict)),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('whatsapp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('source', models.CharField(choices=[('quote', 'Quote'), ('paint_budget', 'Paint Budget Calculator'), ('BookAppointment', 'BookAppointment'), ('WaterProof', 'WaterProof')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
            ],
            options={
                'verbose_name': 'Inspiration',
                'verbose_name_plural': 'Inspirations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
        migrations.CreateModel(
            name='PaintCalculator',
            fields=[
            ],
            options={
                'verbose_name': 'Paint Calculator',
                'verbose_name_plural': 'Paint Calculators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
        migrations.CreateModel(
            name='WaterCalculator',
            fields=[
            ],
            options={
                'verbose_name': 'Water Calculator',
                'verbose_name_plural': 'Water Calculators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
        migrations.CreateModel(
            name='AboutUsBottomVideoBanner',
            fields=[
            ],
            options={
                'verbose_name': 'About Us Bottom Video Banner',
                'verbose_name_plural': 'About Us Bottom Video Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='AboutUsTopBanner',
            fields=[
            ],
            options={
                'verbose_name': 'About Us Top Banner',
                'verbose_name_plural': 'About Us Top Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='ColorPalletsBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Color Pallets Banner',
                'verbose_name_plural': 'Color Pallets Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='ContactUsBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Us Banner',
                'verbose_name_plural': 'Contact Us Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='GalleryBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Gallery Banner',
                'verbose_name_plural': 'Gallery Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='HomeExteriorBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Home Exterior Banner',
                'verbose_name_plural': 'Home Exterior Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='HomeInteriorBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Home Interior Banner',
                'verbose_name_plural': 'Home Interior Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='HomeWaterproofingBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Home Waterproofing Banner',
                'verbose_name_plural': 'Home Waterproofing Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='PaintCalculatorBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Paint Calculator Banner',
                'verbose_name_plural': 'Paint Calculator Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Product Banner',
                'verbose_name_plural': 'Product Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/images/')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aarvi_paint.banner')),
            ],
        ),
        migrations.CreateModel(
            name='ColourCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('colorshade', models.CharField(max_length=200)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colour_codes', to='aarvi_paint.colourpalette')),
            ],
        ),
        migrations.CreateModel(
            name='ColourPaletteWithImages',
            fields=[
            ],
            options={
                'verbose_name': 'Colour Palette With Images',
                'verbose_name_plural': 'Colour Palettes With Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.colourpalette',),
        ),
        migrations.CreateModel(
            name='MultiColorPalette',
            fields=[
            ],
            options={
                'verbose_name': 'Multi-Color Palette',
                'verbose_name_plural': 'Multi-Color Palettes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.colourpalette',),
        ),
        migrations.CreateModel(
            name='ColourPaletteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image (must be less than 10 MB).', upload_to='colour_palette_images/')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aarvi_paint.colourpalette')),
            ],
        ),
        migrations.CreateModel(
            name='ExteriorCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exterior_category_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_images', to='aarvi_paint.exteriorhomecategory')),
            ],
        ),
        migrations.AddField(
            model_name='exteriorhomecategory',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_categories', to='aarvi_paint.home'),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_images/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images_relation', to='aarvi_paint.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeExterior',
            fields=[
            ],
            options={
                'verbose_name': 'Home Exterior',
                'verbose_name_plural': 'Home Exterior',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.CreateModel(
            name='HomeInterior',
            fields=[
            ],
            options={
                'verbose_name': 'Home Interior',
                'verbose_name_plural': 'home interiors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.CreateModel(
            name='HomeWaterProof',
            fields=[
            ],
            options={
                'verbose_name': 'Home Waterproof',
                'verbose_name_plural': 'Home Waterproof',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.CreateModel(
            name='HomeInteriorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeinterior_categories', to='aarvi_paint.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeInteriorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home_interior/feature_images/')),
                ('homeinterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='aarvi_paint.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeInteriorSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='aarvi_paint.homeinteriorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='HomeInteriorSubCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homeinterior_subcategory_images/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aarvi_paint.homeinteriorsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PaintProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_products', to='aarvi_paint.additionalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField()),
                ('long_description', ckeditor.fields.RichTextField()),
                ('keyfeature', models.TextField()),
                ('subcategory', models.JSONField(blank=True, default=list)),
                ('url', models.JSONField()),
                ('colour_palate1', models.CharField(blank=True, max_length=100)),
                ('colour_palate2', models.CharField(blank=True, max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='aarvi_paint.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='type_images/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_images_relation', to='aarvi_paint.home')),
            ],
        ),
        migrations.CreateModel(
            name='PaintBudgetCalculator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_type', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=50)),
                ('surface_condition', models.CharField(choices=[('new', 'New'), ('repaint', 'Repaint')], max_length=50)),
                ('selected_product', models.CharField(max_length=100)),
                ('entered_area', models.FloatField(help_text='Enter area in square meters')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_budgets', to='aarvi_paint.userinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_products', to='aarvi_paint.additionalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='WaterProofCalculator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface_condition', models.CharField(choices=[('Terrace/Horizontal Surface', 'Terrace/Horizontal Surface'), ('Exterior Walls/Vertical Surface', 'Repaint')], max_length=50)),
                ('selected_product', models.CharField(max_length=100)),
                ('entered_area', models.FloatField(help_text='Enter area in square meters')),
                ('description', models.TextField()),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterproof_calculations', to='aarvi_paint.userinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
