# Generated by Django 5.1.7 on 2025-04-28 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subcategory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('additional_info', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('banners', 'Banners'), ('userinfo', 'User Info'), ('colourpalate', 'Color Palate'), ('parallax', 'Parallax'), ('brochure', 'Brochure')], max_length=200)),
                ('metadata', models.JSONField()),
                ('url', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaintBudgetCalculator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_type', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=50)),
                ('surface_condition', models.CharField(choices=[('new', 'New'), ('repaint', 'Repaint')], max_length=50)),
                ('selected_product', models.CharField(max_length=100)),
                ('entered_area', models.FloatField(help_text='Enter area in square meters')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_budgets', to='aarvi_paint.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('keyfeature', models.TextField()),
                ('description', models.TextField()),
                ('url', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='aarvi_paint.category')),
            ],
        ),
    ]
