# Generated by Django 5.2 on 2025-05-05 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Inspiration', 'Inspiration'), ('Testimonial', 'Testimonial'), ('Calculator', 'Calculator'), ('Waterproof', 'Waterproof')], max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminContactDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('google_link', models.URLField()),
                ('social_media_links', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('placement_location', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('url', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.JSONField(blank=True, default=dict)),
                ('uploaded_pdf', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subcategory_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColourPalette',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('colour_code', models.IntegerField()),
                ('colour_code_category', models.CharField(max_length=200)),
                ('url', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parallax',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('quote', 'Quote'), ('paint_budget', 'Paint Budget Calculator'), ('BookAppointment', 'BookAppointment'), ('WaterProof', 'WaterProof')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutUsBottomVideoBanner',
            fields=[
            ],
            options={
                'verbose_name': 'About Us Bottom Video Banner',
                'verbose_name_plural': 'About Us Bottom Video Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='AboutUsTopBanner',
            fields=[
            ],
            options={
                'verbose_name': 'About Us Top Banner',
                'verbose_name_plural': 'About Us Top Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='ColorPalletsBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Color Pallets Banner',
                'verbose_name_plural': 'Color Pallets Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='ContactUsBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Us Banner',
                'verbose_name_plural': 'Contact Us Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='GalleryBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Gallery Banner',
                'verbose_name_plural': 'Gallery Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='HomeExteriorBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Home Exterior Banner',
                'verbose_name_plural': 'Home Exterior Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='HomeInteriorBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Home Interior Banner',
                'verbose_name_plural': 'Home Interior Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='HomeWaterproofingBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Home Waterproofing Banner',
                'verbose_name_plural': 'Home Waterproofing Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Product Banner',
                'verbose_name_plural': 'Product Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.banner',),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('WaterProf', 'WaterProf')], max_length=200)),
                ('category_name', models.CharField(max_length=100)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('category_images', models.JSONField(blank=True, default=dict)),
                ('type_images', models.JSONField(blank=True, default=dict)),
                ('type_description', models.TextField()),
                ('title_type', models.CharField(max_length=200)),
                ('banners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='aarvi_paint.banner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('keyfeature', models.TextField()),
                ('description', models.TextField()),
                ('url', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='aarvi_paint.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaintBudgetCalculator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_type', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=50)),
                ('surface_condition', models.CharField(choices=[('new', 'New'), ('repaint', 'Repaint')], max_length=50)),
                ('selected_product', models.CharField(max_length=100)),
                ('entered_area', models.FloatField(help_text='Enter area in square meters')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_budgets', to='aarvi_paint.userinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterProofCalculator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface_condition', models.CharField(choices=[('Terrace/Horizontal Surface', 'Terrace/Horizontal Surface'), ('Exterior Walls/Vertical Surface', 'Repaint')], max_length=50)),
                ('selected_product', models.CharField(max_length=100)),
                ('entered_area', models.FloatField(help_text='Enter area in square meters')),
                ('description', models.TextField()),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterproof_calculations', to='aarvi_paint.userinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
