# Generated by Django 5.2 on 2025-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0002_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
