# Generated by Django 5.2 on 2025-05-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0003_bannerimage_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='alt_text',
        ),
    ]
