# Generated by Django 5.2 on 2025-05-06 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0004_remove_bannerimage_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInterior',
            fields=[
            ],
            options={
                'verbose_name': 'Home Interior',
                'verbose_name_plural': 'home interiors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.AlterField(
            model_name='home',
            name='banners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='aarvi_paint.banner'),
        ),
    ]
