# Generated by Django 5.2 on 2025-05-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0005_homeinterior_alter_home_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourPaletteWithImages',
            fields=[
            ],
            options={
                'verbose_name': 'Colour Palette With Images',
                'verbose_name_plural': 'Colour Palettes With Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.colourpalette',),
        ),
        migrations.CreateModel(
            name='HomeExteriorData',
            fields=[
            ],
            options={
                'verbose_name': 'Home Exterior Data',
                'verbose_name_plural': 'home exterior datas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.CreateModel(
            name='HomeInteriorColorCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Home Interior Color Category',
                'verbose_name_plural': 'home interior color categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.CreateModel(
            name='HomeInteriorDifferentRoom',
            fields=[
            ],
            options={
                'verbose_name': 'Home Interior Different Room',
                'verbose_name_plural': 'home interiors Different Rooms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_images/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images_set', to='aarvi_paint.home')),
            ],
        ),
        migrations.CreateModel(
            name='ColourPaletteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colour_palette_images/')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aarvi_paint.colourpalette')),
            ],
        ),
    ]
