# Generated by Django 5.2 on 2025-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0006_colourpalettewithimages_homeexteriordata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourpalette',
            name='colour_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='colourpalette',
            name='colour_code_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='colourpalette',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='colourpalette',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
