# Generated by Django 5.2 on 2025-05-06 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0007_alter_colourpalette_colour_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourPaletteProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Colour Palette (Enhanced)',
                'verbose_name_plural': 'Colour Palettes (Enhanced)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.colourpalette',),
        ),
        migrations.CreateModel(
            name='MultiColorPalette',
            fields=[
            ],
            options={
                'verbose_name': 'Multi-Color Palette',
                'verbose_name_plural': 'Multi-Color Palettes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.colourpalette',),
        ),
        migrations.CreateModel(
            name='ColourCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colour_codes', to='aarvi_paint.colourpalette')),
            ],
        ),
    ]
