# Generated by Django 5.2 on 2025-05-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0008_colourpaletteproxy_multicolorpalette_colourcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Custom Home Entry',
                'verbose_name_plural': 'Custom Home Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.AlterField(
            model_name='home',
            name='category_images',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='subcategory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='type_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='type_images',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='TypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='type_images/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_image_set', to='aarvi_paint.home')),
            ],
        ),
    ]
