# Generated by Django 5.2 on 2025-05-07 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0009_homeproxy_alter_home_category_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.JSONField(blank=True, default=dict, null=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterproofHome',
            fields=[
            ],
            options={
                'verbose_name': 'Waterproof Home',
                'verbose_name_plural': 'Waterproof Homes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.home',),
        ),
        migrations.AlterModelOptions(
            name='homeproxy',
            options={'verbose_name': 'Home Custom View', 'verbose_name_plural': 'Homes Custom View'},
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images_relation', to='aarvi_paint.home'),
        ),
        migrations.AlterField(
            model_name='typeimage',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_images_relation', to='aarvi_paint.home'),
        ),
    ]
