# Generated by Django 5.2 on 2025-05-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0010_aboutus_waterproofhome_alter_homeproxy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
            ],
            options={
                'verbose_name': 'Paint Calculator',
                'verbose_name_plural': 'Paint Calculators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
            ],
            options={
                'verbose_name': 'Inspiration',
                'verbose_name_plural': 'Inspirations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
        migrations.CreateModel(
            name='WaterCalculator',
            fields=[
            ],
            options={
                'verbose_name': 'Water Calculator',
                'verbose_name_plural': 'Water Calculators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
        migrations.CreateModel(
            name='WaterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_products', to='aarvi_paint.additionalinfo')),
            ],
        ),
    ]
