# Generated by Django 5.2 on 2025-05-08 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarvi_paint', '0011_calculator_inspiration_testimonial_watercalculator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_products', to='aarvi_paint.additionalinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Calculator',
        ),
        migrations.CreateModel(
            name='PaintCalculator',
            fields=[
            ],
            options={
                'verbose_name': 'Paint Calculator',
                'verbose_name_plural': 'Paint Calculators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aarvi_paint.additionalinfo',),
        ),
    ]
